'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace spc2011
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Customer", [Namespace]:="http://schemas.datacontract.org/2004/07/spc2011"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Customer
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Customer_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Date_createdField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Date_modifiedField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Customer_id() As Integer
            Get
                Return Me.Customer_idField
            End Get
            Set
                If (Me.Customer_idField.Equals(value) <> true) Then
                    Me.Customer_idField = value
                    Me.RaisePropertyChanged("Customer_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Date_created() As Date
            Get
                Return Me.Date_createdField
            End Get
            Set
                If (Me.Date_createdField.Equals(value) <> true) Then
                    Me.Date_createdField = value
                    Me.RaisePropertyChanged("Date_created")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Date_modified() As Date
            Get
                Return Me.Date_modifiedField
            End Get
            Set
                If (Me.Date_modifiedField.Equals(value) <> true) Then
                    Me.Date_modifiedField = value
                    Me.RaisePropertyChanged("Date_modified")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Contact", [Namespace]:="http://schemas.datacontract.org/2004/07/spc2011"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Contact
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Billing_contactField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Contact_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Customer_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartmentField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaxField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private First_nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Friendly_nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private General_contactField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Home_phoneField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Last_nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Management_contactField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Mobile_phoneField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Sales_contactField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SalutationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Technical_contactField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TitleField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Web_siteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Work_extensionField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Work_phoneField As Long
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Billing_contact() As Boolean
            Get
                Return Me.Billing_contactField
            End Get
            Set
                If (Me.Billing_contactField.Equals(value) <> true) Then
                    Me.Billing_contactField = value
                    Me.RaisePropertyChanged("Billing_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Contact_id() As Integer
            Get
                Return Me.Contact_idField
            End Get
            Set
                If (Me.Contact_idField.Equals(value) <> true) Then
                    Me.Contact_idField = value
                    Me.RaisePropertyChanged("Contact_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Customer_id() As Integer
            Get
                Return Me.Customer_idField
            End Get
            Set
                If (Me.Customer_idField.Equals(value) <> true) Then
                    Me.Customer_idField = value
                    Me.RaisePropertyChanged("Customer_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Department() As String
            Get
                Return Me.DepartmentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartmentField, value) <> true) Then
                    Me.DepartmentField = value
                    Me.RaisePropertyChanged("Department")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fax() As Long
            Get
                Return Me.FaxField
            End Get
            Set
                If (Me.FaxField.Equals(value) <> true) Then
                    Me.FaxField = value
                    Me.RaisePropertyChanged("Fax")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property First_name() As String
            Get
                Return Me.First_nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.First_nameField, value) <> true) Then
                    Me.First_nameField = value
                    Me.RaisePropertyChanged("First_name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Friendly_name() As String
            Get
                Return Me.Friendly_nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Friendly_nameField, value) <> true) Then
                    Me.Friendly_nameField = value
                    Me.RaisePropertyChanged("Friendly_name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property General_contact() As Boolean
            Get
                Return Me.General_contactField
            End Get
            Set
                If (Me.General_contactField.Equals(value) <> true) Then
                    Me.General_contactField = value
                    Me.RaisePropertyChanged("General_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Home_phone() As Long
            Get
                Return Me.Home_phoneField
            End Get
            Set
                If (Me.Home_phoneField.Equals(value) <> true) Then
                    Me.Home_phoneField = value
                    Me.RaisePropertyChanged("Home_phone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Last_name() As String
            Get
                Return Me.Last_nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Last_nameField, value) <> true) Then
                    Me.Last_nameField = value
                    Me.RaisePropertyChanged("Last_name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Management_contact() As Boolean
            Get
                Return Me.Management_contactField
            End Get
            Set
                If (Me.Management_contactField.Equals(value) <> true) Then
                    Me.Management_contactField = value
                    Me.RaisePropertyChanged("Management_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Mobile_phone() As Long
            Get
                Return Me.Mobile_phoneField
            End Get
            Set
                If (Me.Mobile_phoneField.Equals(value) <> true) Then
                    Me.Mobile_phoneField = value
                    Me.RaisePropertyChanged("Mobile_phone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sales_contact() As Boolean
            Get
                Return Me.Sales_contactField
            End Get
            Set
                If (Me.Sales_contactField.Equals(value) <> true) Then
                    Me.Sales_contactField = value
                    Me.RaisePropertyChanged("Sales_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Salutation() As String
            Get
                Return Me.SalutationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SalutationField, value) <> true) Then
                    Me.SalutationField = value
                    Me.RaisePropertyChanged("Salutation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Technical_contact() As Boolean
            Get
                Return Me.Technical_contactField
            End Get
            Set
                If (Me.Technical_contactField.Equals(value) <> true) Then
                    Me.Technical_contactField = value
                    Me.RaisePropertyChanged("Technical_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Web_site() As String
            Get
                Return Me.Web_siteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Web_siteField, value) <> true) Then
                    Me.Web_siteField = value
                    Me.RaisePropertyChanged("Web_site")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Work_extension() As Integer
            Get
                Return Me.Work_extensionField
            End Get
            Set
                If (Me.Work_extensionField.Equals(value) <> true) Then
                    Me.Work_extensionField = value
                    Me.RaisePropertyChanged("Work_extension")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Work_phone() As Long
            Get
                Return Me.Work_phoneField
            End Get
            Set
                If (Me.Work_phoneField.Equals(value) <> true) Then
                    Me.Work_phoneField = value
                    Me.RaisePropertyChanged("Work_phone")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Method_status", [Namespace]:="http://schemas.datacontract.org/2004/07/spc2011")>  _
    Public Enum Method_status As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Success = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Info_error = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Fatal_error = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="spc2011.ISynergyServer")>  _
    Public Interface ISynergyServer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISynergyServer/GetAllCustomers", ReplyAction:="http://tempuri.org/ISynergyServer/GetAllCustomersResponse")>  _
        Function GetAllCustomers() As <System.ServiceModel.MessageParameterAttribute(Name:="a_customers")> System.Collections.Generic.List(Of spc2011.Customer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISynergyServer/GetCustomerContacts", ReplyAction:="http://tempuri.org/ISynergyServer/GetCustomerContactsResponse")>  _
        Function GetCustomerContacts(ByVal a_customer_id As Integer) As <System.ServiceModel.MessageParameterAttribute(Name:="a_contacts")> System.Collections.Generic.List(Of spc2011.Contact)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISynergyServer/GetContactForUpdate", ReplyAction:="http://tempuri.org/ISynergyServer/GetContactForUpdateResponse")>  _
        Function GetContactForUpdate(<System.Runtime.InteropServices.OutAttribute()> ByRef a_contact As spc2011.Contact, <System.Runtime.InteropServices.OutAttribute()> ByRef a_grfa() As Byte, <System.Runtime.InteropServices.OutAttribute()> ByRef a_message As String, ByVal a_customer_id As Integer, ByVal a_contact_id As Integer) As spc2011.Method_status
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISynergyServer/UpdateContact", ReplyAction:="http://tempuri.org/ISynergyServer/UpdateContactResponse")>  _
        Function UpdateContact(ByRef a_contact As spc2011.Contact, ByRef a_grfa() As Byte, <System.Runtime.InteropServices.OutAttribute()> ByRef a_message As String) As spc2011.Method_status
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISynergyServerChannel
        Inherits spc2011.ISynergyServer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SynergyServerClient
        Inherits System.ServiceModel.ClientBase(Of spc2011.ISynergyServer)
        Implements spc2011.ISynergyServer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetAllCustomers() As System.Collections.Generic.List(Of spc2011.Customer) Implements spc2011.ISynergyServer.GetAllCustomers
            Return MyBase.Channel.GetAllCustomers
        End Function
        
        Public Function GetCustomerContacts(ByVal a_customer_id As Integer) As System.Collections.Generic.List(Of spc2011.Contact) Implements spc2011.ISynergyServer.GetCustomerContacts
            Return MyBase.Channel.GetCustomerContacts(a_customer_id)
        End Function
        
        Public Function GetContactForUpdate(<System.Runtime.InteropServices.OutAttribute()> ByRef a_contact As spc2011.Contact, <System.Runtime.InteropServices.OutAttribute()> ByRef a_grfa() As Byte, <System.Runtime.InteropServices.OutAttribute()> ByRef a_message As String, ByVal a_customer_id As Integer, ByVal a_contact_id As Integer) As spc2011.Method_status Implements spc2011.ISynergyServer.GetContactForUpdate
            Return MyBase.Channel.GetContactForUpdate(a_contact, a_grfa, a_message, a_customer_id, a_contact_id)
        End Function
        
        Public Function UpdateContact(ByRef a_contact As spc2011.Contact, ByRef a_grfa() As Byte, <System.Runtime.InteropServices.OutAttribute()> ByRef a_message As String) As spc2011.Method_status Implements spc2011.ISynergyServer.UpdateContact
            Return MyBase.Channel.UpdateContact(a_contact, a_grfa, a_message)
        End Function
    End Class
End Namespace
