//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.spc2011 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Customer_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.DateTime Date_createdField;
        
        private System.DateTime Date_modifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Replication_keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Noname_001Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Customer_id {
            get {
                return this.Customer_idField;
            }
            set {
                if ((this.Customer_idField.Equals(value) != true)) {
                    this.Customer_idField = value;
                    this.RaisePropertyChanged("Customer_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Date_created {
            get {
                return this.Date_createdField;
            }
            set {
                if ((this.Date_createdField.Equals(value) != true)) {
                    this.Date_createdField = value;
                    this.RaisePropertyChanged("Date_created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Date_modified {
            get {
                return this.Date_modifiedField;
            }
            set {
                if ((this.Date_modifiedField.Equals(value) != true)) {
                    this.Date_modifiedField = value;
                    this.RaisePropertyChanged("Date_modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Replication_key {
            get {
                return this.Replication_keyField;
            }
            set {
                if ((object.ReferenceEquals(this.Replication_keyField, value) != true)) {
                    this.Replication_keyField = value;
                    this.RaisePropertyChanged("Replication_key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Noname_001 {
            get {
                return this.Noname_001Field;
            }
            set {
                if ((object.ReferenceEquals(this.Noname_001Field, value) != true)) {
                    this.Noname_001Field = value;
                    this.RaisePropertyChanged("Noname_001");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Contact_idField;
        
        private int Customer_idField;
        
        private int Address_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalutationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Friendly_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        private long Work_phoneField;
        
        private int Work_extensionField;
        
        private long Mobile_phoneField;
        
        private long Home_phoneField;
        
        private long FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Web_siteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Picture_fileField;
        
        private bool Management_contactField;
        
        private bool Technical_contactField;
        
        private bool Sales_contactField;
        
        private bool Billing_contactField;
        
        private bool General_contactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Replication_keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Noname_001Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Contact_id {
            get {
                return this.Contact_idField;
            }
            set {
                if ((this.Contact_idField.Equals(value) != true)) {
                    this.Contact_idField = value;
                    this.RaisePropertyChanged("Contact_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Customer_id {
            get {
                return this.Customer_idField;
            }
            set {
                if ((this.Customer_idField.Equals(value) != true)) {
                    this.Customer_idField = value;
                    this.RaisePropertyChanged("Customer_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Address_id {
            get {
                return this.Address_idField;
            }
            set {
                if ((this.Address_idField.Equals(value) != true)) {
                    this.Address_idField = value;
                    this.RaisePropertyChanged("Address_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Salutation {
            get {
                return this.SalutationField;
            }
            set {
                if ((object.ReferenceEquals(this.SalutationField, value) != true)) {
                    this.SalutationField = value;
                    this.RaisePropertyChanged("Salutation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string First_name {
            get {
                return this.First_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_nameField, value) != true)) {
                    this.First_nameField = value;
                    this.RaisePropertyChanged("First_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Last_name {
            get {
                return this.Last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_nameField, value) != true)) {
                    this.Last_nameField = value;
                    this.RaisePropertyChanged("Last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Friendly_name {
            get {
                return this.Friendly_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Friendly_nameField, value) != true)) {
                    this.Friendly_nameField = value;
                    this.RaisePropertyChanged("Friendly_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public long Work_phone {
            get {
                return this.Work_phoneField;
            }
            set {
                if ((this.Work_phoneField.Equals(value) != true)) {
                    this.Work_phoneField = value;
                    this.RaisePropertyChanged("Work_phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int Work_extension {
            get {
                return this.Work_extensionField;
            }
            set {
                if ((this.Work_extensionField.Equals(value) != true)) {
                    this.Work_extensionField = value;
                    this.RaisePropertyChanged("Work_extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public long Mobile_phone {
            get {
                return this.Mobile_phoneField;
            }
            set {
                if ((this.Mobile_phoneField.Equals(value) != true)) {
                    this.Mobile_phoneField = value;
                    this.RaisePropertyChanged("Mobile_phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public long Home_phone {
            get {
                return this.Home_phoneField;
            }
            set {
                if ((this.Home_phoneField.Equals(value) != true)) {
                    this.Home_phoneField = value;
                    this.RaisePropertyChanged("Home_phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public long Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((this.FaxField.Equals(value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Web_site {
            get {
                return this.Web_siteField;
            }
            set {
                if ((object.ReferenceEquals(this.Web_siteField, value) != true)) {
                    this.Web_siteField = value;
                    this.RaisePropertyChanged("Web_site");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Picture_file {
            get {
                return this.Picture_fileField;
            }
            set {
                if ((object.ReferenceEquals(this.Picture_fileField, value) != true)) {
                    this.Picture_fileField = value;
                    this.RaisePropertyChanged("Picture_file");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public bool Management_contact {
            get {
                return this.Management_contactField;
            }
            set {
                if ((this.Management_contactField.Equals(value) != true)) {
                    this.Management_contactField = value;
                    this.RaisePropertyChanged("Management_contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public bool Technical_contact {
            get {
                return this.Technical_contactField;
            }
            set {
                if ((this.Technical_contactField.Equals(value) != true)) {
                    this.Technical_contactField = value;
                    this.RaisePropertyChanged("Technical_contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public bool Sales_contact {
            get {
                return this.Sales_contactField;
            }
            set {
                if ((this.Sales_contactField.Equals(value) != true)) {
                    this.Sales_contactField = value;
                    this.RaisePropertyChanged("Sales_contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public bool Billing_contact {
            get {
                return this.Billing_contactField;
            }
            set {
                if ((this.Billing_contactField.Equals(value) != true)) {
                    this.Billing_contactField = value;
                    this.RaisePropertyChanged("Billing_contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public bool General_contact {
            get {
                return this.General_contactField;
            }
            set {
                if ((this.General_contactField.Equals(value) != true)) {
                    this.General_contactField = value;
                    this.RaisePropertyChanged("General_contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Replication_key {
            get {
                return this.Replication_keyField;
            }
            set {
                if ((object.ReferenceEquals(this.Replication_keyField, value) != true)) {
                    this.Replication_keyField = value;
                    this.RaisePropertyChanged("Replication_key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string Noname_001 {
            get {
                return this.Noname_001Field;
            }
            set {
                if ((object.ReferenceEquals(this.Noname_001Field, value) != true)) {
                    this.Noname_001Field = value;
                    this.RaisePropertyChanged("Noname_001");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Method_status", Namespace="http://tempuri.org/")]
    public enum Method_status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info_error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fatal_error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="spc2011.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllCustomersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCustomers", ReplyAction="*")]
        ClientApp.spc2011.GetAllCustomersResponse GetAllCustomers(ClientApp.spc2011.GetAllCustomersRequest request);
        
        // CODEGEN: Generating message contract since element name GetCustomerContactsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerContacts", ReplyAction="*")]
        ClientApp.spc2011.GetCustomerContactsResponse GetCustomerContacts(ClientApp.spc2011.GetCustomerContactsRequest request);
        
        // CODEGEN: Generating message contract since element name contact from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactForUpdate", ReplyAction="*")]
        ClientApp.spc2011.GetContactForUpdateResponse GetContactForUpdate(ClientApp.spc2011.GetContactForUpdateRequest request);
        
        // CODEGEN: Generating message contract since element name contact from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateContact", ReplyAction="*")]
        ClientApp.spc2011.UpdateContactResponse UpdateContact(ClientApp.spc2011.UpdateContactRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCustomers", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.spc2011.GetAllCustomersRequestBody Body;
        
        public GetAllCustomersRequest() {
        }
        
        public GetAllCustomersRequest(ClientApp.spc2011.GetAllCustomersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCustomersRequestBody {
        
        public GetAllCustomersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCustomersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.spc2011.GetAllCustomersResponseBody Body;
        
        public GetAllCustomersResponse() {
        }
        
        public GetAllCustomersResponse(ClientApp.spc2011.GetAllCustomersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCustomersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ClientApp.spc2011.Customer> GetAllCustomersResult;
        
        public GetAllCustomersResponseBody() {
        }
        
        public GetAllCustomersResponseBody(System.Collections.Generic.List<ClientApp.spc2011.Customer> GetAllCustomersResult) {
            this.GetAllCustomersResult = GetAllCustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerContactsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerContacts", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.spc2011.GetCustomerContactsRequestBody Body;
        
        public GetCustomerContactsRequest() {
        }
        
        public GetCustomerContactsRequest(ClientApp.spc2011.GetCustomerContactsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerContactsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CustomerId;
        
        public GetCustomerContactsRequestBody() {
        }
        
        public GetCustomerContactsRequestBody(int CustomerId) {
            this.CustomerId = CustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerContactsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerContactsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.spc2011.GetCustomerContactsResponseBody Body;
        
        public GetCustomerContactsResponse() {
        }
        
        public GetCustomerContactsResponse(ClientApp.spc2011.GetCustomerContactsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerContactsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ClientApp.spc2011.Contact> GetCustomerContactsResult;
        
        public GetCustomerContactsResponseBody() {
        }
        
        public GetCustomerContactsResponseBody(System.Collections.Generic.List<ClientApp.spc2011.Contact> GetCustomerContactsResult) {
            this.GetCustomerContactsResult = GetCustomerContactsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactForUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactForUpdate", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.spc2011.GetContactForUpdateRequestBody Body;
        
        public GetContactForUpdateRequest() {
        }
        
        public GetContactForUpdateRequest(ClientApp.spc2011.GetContactForUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContactForUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int contactId;
        
        public GetContactForUpdateRequestBody() {
        }
        
        public GetContactForUpdateRequestBody(int customerId, int contactId) {
            this.customerId = customerId;
            this.contactId = contactId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactForUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactForUpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.spc2011.GetContactForUpdateResponseBody Body;
        
        public GetContactForUpdateResponse() {
        }
        
        public GetContactForUpdateResponse(ClientApp.spc2011.GetContactForUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContactForUpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ClientApp.spc2011.Method_status GetContactForUpdateResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ClientApp.spc2011.Contact contact;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] grfa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msg;
        
        public GetContactForUpdateResponseBody() {
        }
        
        public GetContactForUpdateResponseBody(ClientApp.spc2011.Method_status GetContactForUpdateResult, ClientApp.spc2011.Contact contact, byte[] grfa, string msg) {
            this.GetContactForUpdateResult = GetContactForUpdateResult;
            this.contact = contact;
            this.grfa = grfa;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContactRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContact", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.spc2011.UpdateContactRequestBody Body;
        
        public UpdateContactRequest() {
        }
        
        public UpdateContactRequest(ClientApp.spc2011.UpdateContactRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateContactRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientApp.spc2011.Contact contact;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] grfa;
        
        public UpdateContactRequestBody() {
        }
        
        public UpdateContactRequestBody(ClientApp.spc2011.Contact contact, byte[] grfa) {
            this.contact = contact;
            this.grfa = grfa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContactResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.spc2011.UpdateContactResponseBody Body;
        
        public UpdateContactResponse() {
        }
        
        public UpdateContactResponse(ClientApp.spc2011.UpdateContactResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateContactResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ClientApp.spc2011.Method_status UpdateContactResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ClientApp.spc2011.Contact contact;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] grfa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msg;
        
        public UpdateContactResponseBody() {
        }
        
        public UpdateContactResponseBody(ClientApp.spc2011.Method_status UpdateContactResult, ClientApp.spc2011.Contact contact, byte[] grfa, string msg) {
            this.UpdateContactResult = UpdateContactResult;
            this.contact = contact;
            this.grfa = grfa;
            this.msg = msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ClientApp.spc2011.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ClientApp.spc2011.WebServiceSoap>, ClientApp.spc2011.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.spc2011.GetAllCustomersResponse ClientApp.spc2011.WebServiceSoap.GetAllCustomers(ClientApp.spc2011.GetAllCustomersRequest request) {
            return base.Channel.GetAllCustomers(request);
        }
        
        public System.Collections.Generic.List<ClientApp.spc2011.Customer> GetAllCustomers() {
            ClientApp.spc2011.GetAllCustomersRequest inValue = new ClientApp.spc2011.GetAllCustomersRequest();
            inValue.Body = new ClientApp.spc2011.GetAllCustomersRequestBody();
            ClientApp.spc2011.GetAllCustomersResponse retVal = ((ClientApp.spc2011.WebServiceSoap)(this)).GetAllCustomers(inValue);
            return retVal.Body.GetAllCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.spc2011.GetCustomerContactsResponse ClientApp.spc2011.WebServiceSoap.GetCustomerContacts(ClientApp.spc2011.GetCustomerContactsRequest request) {
            return base.Channel.GetCustomerContacts(request);
        }
        
        public System.Collections.Generic.List<ClientApp.spc2011.Contact> GetCustomerContacts(int CustomerId) {
            ClientApp.spc2011.GetCustomerContactsRequest inValue = new ClientApp.spc2011.GetCustomerContactsRequest();
            inValue.Body = new ClientApp.spc2011.GetCustomerContactsRequestBody();
            inValue.Body.CustomerId = CustomerId;
            ClientApp.spc2011.GetCustomerContactsResponse retVal = ((ClientApp.spc2011.WebServiceSoap)(this)).GetCustomerContacts(inValue);
            return retVal.Body.GetCustomerContactsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.spc2011.GetContactForUpdateResponse ClientApp.spc2011.WebServiceSoap.GetContactForUpdate(ClientApp.spc2011.GetContactForUpdateRequest request) {
            return base.Channel.GetContactForUpdate(request);
        }
        
        public ClientApp.spc2011.Method_status GetContactForUpdate(int customerId, int contactId, out ClientApp.spc2011.Contact contact, out byte[] grfa, out string msg) {
            ClientApp.spc2011.GetContactForUpdateRequest inValue = new ClientApp.spc2011.GetContactForUpdateRequest();
            inValue.Body = new ClientApp.spc2011.GetContactForUpdateRequestBody();
            inValue.Body.customerId = customerId;
            inValue.Body.contactId = contactId;
            ClientApp.spc2011.GetContactForUpdateResponse retVal = ((ClientApp.spc2011.WebServiceSoap)(this)).GetContactForUpdate(inValue);
            contact = retVal.Body.contact;
            grfa = retVal.Body.grfa;
            msg = retVal.Body.msg;
            return retVal.Body.GetContactForUpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.spc2011.UpdateContactResponse ClientApp.spc2011.WebServiceSoap.UpdateContact(ClientApp.spc2011.UpdateContactRequest request) {
            return base.Channel.UpdateContact(request);
        }
        
        public ClientApp.spc2011.Method_status UpdateContact(ref ClientApp.spc2011.Contact contact, ref byte[] grfa, out string msg) {
            ClientApp.spc2011.UpdateContactRequest inValue = new ClientApp.spc2011.UpdateContactRequest();
            inValue.Body = new ClientApp.spc2011.UpdateContactRequestBody();
            inValue.Body.contact = contact;
            inValue.Body.grfa = grfa;
            ClientApp.spc2011.UpdateContactResponse retVal = ((ClientApp.spc2011.WebServiceSoap)(this)).UpdateContact(inValue);
            contact = retVal.Body.contact;
            grfa = retVal.Body.grfa;
            msg = retVal.Body.msg;
            return retVal.Body.UpdateContactResult;
        }
    }
}
