'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace spc2011
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Address", [Namespace]:="http://schemas.datacontract.org/2004/07/spc2011"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Address
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Active_dateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Address1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Address2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Address3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Address_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Address_typeField As spc2011.Address_type
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Billing_addressField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CountryField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Customer_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Mailing_addressField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Main_addressField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Postal_codeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Replication_keyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Satellite_officeField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StateField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Active_date() As Date
            Get
                Return Me.Active_dateField
            End Get
            Set
                If (Me.Active_dateField.Equals(value) <> true) Then
                    Me.Active_dateField = value
                    Me.RaisePropertyChanged("Active_date")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address1() As String
            Get
                Return Me.Address1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Address1Field, value) <> true) Then
                    Me.Address1Field = value
                    Me.RaisePropertyChanged("Address1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address2() As String
            Get
                Return Me.Address2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Address2Field, value) <> true) Then
                    Me.Address2Field = value
                    Me.RaisePropertyChanged("Address2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address3() As String
            Get
                Return Me.Address3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Address3Field, value) <> true) Then
                    Me.Address3Field = value
                    Me.RaisePropertyChanged("Address3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address_id() As Integer
            Get
                Return Me.Address_idField
            End Get
            Set
                If (Me.Address_idField.Equals(value) <> true) Then
                    Me.Address_idField = value
                    Me.RaisePropertyChanged("Address_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address_type() As spc2011.Address_type
            Get
                Return Me.Address_typeField
            End Get
            Set
                If (Me.Address_typeField.Equals(value) <> true) Then
                    Me.Address_typeField = value
                    Me.RaisePropertyChanged("Address_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Billing_address() As Boolean
            Get
                Return Me.Billing_addressField
            End Get
            Set
                If (Me.Billing_addressField.Equals(value) <> true) Then
                    Me.Billing_addressField = value
                    Me.RaisePropertyChanged("Billing_address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property City() As String
            Get
                Return Me.CityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CityField, value) <> true) Then
                    Me.CityField = value
                    Me.RaisePropertyChanged("City")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Country() As String
            Get
                Return Me.CountryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryField, value) <> true) Then
                    Me.CountryField = value
                    Me.RaisePropertyChanged("Country")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Customer_id() As Integer
            Get
                Return Me.Customer_idField
            End Get
            Set
                If (Me.Customer_idField.Equals(value) <> true) Then
                    Me.Customer_idField = value
                    Me.RaisePropertyChanged("Customer_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Mailing_address() As Boolean
            Get
                Return Me.Mailing_addressField
            End Get
            Set
                If (Me.Mailing_addressField.Equals(value) <> true) Then
                    Me.Mailing_addressField = value
                    Me.RaisePropertyChanged("Mailing_address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Main_address() As Boolean
            Get
                Return Me.Main_addressField
            End Get
            Set
                If (Me.Main_addressField.Equals(value) <> true) Then
                    Me.Main_addressField = value
                    Me.RaisePropertyChanged("Main_address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Postal_code() As String
            Get
                Return Me.Postal_codeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Postal_codeField, value) <> true) Then
                    Me.Postal_codeField = value
                    Me.RaisePropertyChanged("Postal_code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Replication_key() As String
            Get
                Return Me.Replication_keyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Replication_keyField, value) <> true) Then
                    Me.Replication_keyField = value
                    Me.RaisePropertyChanged("Replication_key")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Satellite_office() As Boolean
            Get
                Return Me.Satellite_officeField
            End Get
            Set
                If (Me.Satellite_officeField.Equals(value) <> true) Then
                    Me.Satellite_officeField = value
                    Me.RaisePropertyChanged("Satellite_office")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property State() As String
            Get
                Return Me.StateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StateField, value) <> true) Then
                    Me.StateField = value
                    Me.RaisePropertyChanged("State")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Address_type", [Namespace]:="http://schemas.datacontract.org/2004/07/spc2011")>  _
    Public Enum Address_type As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Business = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Home = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Other = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Method_status", [Namespace]:="http://schemas.datacontract.org/2004/07/spc2011")>  _
    Public Enum Method_status As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Success = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Info_error = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Fatal_error = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Customer", [Namespace]:="http://schemas.datacontract.org/2004/07/spc2011"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Customer
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Customer_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Date_createdField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Date_modifiedField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Noname_001Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Replication_keyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Customer_id() As Integer
            Get
                Return Me.Customer_idField
            End Get
            Set
                If (Me.Customer_idField.Equals(value) <> true) Then
                    Me.Customer_idField = value
                    Me.RaisePropertyChanged("Customer_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Date_created() As Date
            Get
                Return Me.Date_createdField
            End Get
            Set
                If (Me.Date_createdField.Equals(value) <> true) Then
                    Me.Date_createdField = value
                    Me.RaisePropertyChanged("Date_created")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Date_modified() As Date
            Get
                Return Me.Date_modifiedField
            End Get
            Set
                If (Me.Date_modifiedField.Equals(value) <> true) Then
                    Me.Date_modifiedField = value
                    Me.RaisePropertyChanged("Date_modified")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Noname_001() As String
            Get
                Return Me.Noname_001Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Noname_001Field, value) <> true) Then
                    Me.Noname_001Field = value
                    Me.RaisePropertyChanged("Noname_001")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Replication_key() As String
            Get
                Return Me.Replication_keyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Replication_keyField, value) <> true) Then
                    Me.Replication_keyField = value
                    Me.RaisePropertyChanged("Replication_key")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Contact", [Namespace]:="http://schemas.datacontract.org/2004/07/spc2011"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Contact
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Address_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Billing_contactField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Contact_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Customer_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartmentField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaxField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private First_nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Friendly_nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private General_contactField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Home_phoneField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Last_nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Management_contactField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Mobile_phoneField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Noname_001Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Picture_fileField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Replication_keyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Sales_contactField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SalutationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Technical_contactField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TitleField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Web_siteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Work_extensionField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Work_phoneField As Long
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address_id() As Integer
            Get
                Return Me.Address_idField
            End Get
            Set
                If (Me.Address_idField.Equals(value) <> true) Then
                    Me.Address_idField = value
                    Me.RaisePropertyChanged("Address_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Billing_contact() As Boolean
            Get
                Return Me.Billing_contactField
            End Get
            Set
                If (Me.Billing_contactField.Equals(value) <> true) Then
                    Me.Billing_contactField = value
                    Me.RaisePropertyChanged("Billing_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Contact_id() As Integer
            Get
                Return Me.Contact_idField
            End Get
            Set
                If (Me.Contact_idField.Equals(value) <> true) Then
                    Me.Contact_idField = value
                    Me.RaisePropertyChanged("Contact_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Customer_id() As Integer
            Get
                Return Me.Customer_idField
            End Get
            Set
                If (Me.Customer_idField.Equals(value) <> true) Then
                    Me.Customer_idField = value
                    Me.RaisePropertyChanged("Customer_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Department() As String
            Get
                Return Me.DepartmentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartmentField, value) <> true) Then
                    Me.DepartmentField = value
                    Me.RaisePropertyChanged("Department")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fax() As Long
            Get
                Return Me.FaxField
            End Get
            Set
                If (Me.FaxField.Equals(value) <> true) Then
                    Me.FaxField = value
                    Me.RaisePropertyChanged("Fax")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property First_name() As String
            Get
                Return Me.First_nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.First_nameField, value) <> true) Then
                    Me.First_nameField = value
                    Me.RaisePropertyChanged("First_name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Friendly_name() As String
            Get
                Return Me.Friendly_nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Friendly_nameField, value) <> true) Then
                    Me.Friendly_nameField = value
                    Me.RaisePropertyChanged("Friendly_name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property General_contact() As Boolean
            Get
                Return Me.General_contactField
            End Get
            Set
                If (Me.General_contactField.Equals(value) <> true) Then
                    Me.General_contactField = value
                    Me.RaisePropertyChanged("General_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Home_phone() As Long
            Get
                Return Me.Home_phoneField
            End Get
            Set
                If (Me.Home_phoneField.Equals(value) <> true) Then
                    Me.Home_phoneField = value
                    Me.RaisePropertyChanged("Home_phone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Last_name() As String
            Get
                Return Me.Last_nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Last_nameField, value) <> true) Then
                    Me.Last_nameField = value
                    Me.RaisePropertyChanged("Last_name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Management_contact() As Boolean
            Get
                Return Me.Management_contactField
            End Get
            Set
                If (Me.Management_contactField.Equals(value) <> true) Then
                    Me.Management_contactField = value
                    Me.RaisePropertyChanged("Management_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Mobile_phone() As Long
            Get
                Return Me.Mobile_phoneField
            End Get
            Set
                If (Me.Mobile_phoneField.Equals(value) <> true) Then
                    Me.Mobile_phoneField = value
                    Me.RaisePropertyChanged("Mobile_phone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Noname_001() As String
            Get
                Return Me.Noname_001Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Noname_001Field, value) <> true) Then
                    Me.Noname_001Field = value
                    Me.RaisePropertyChanged("Noname_001")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Picture_file() As String
            Get
                Return Me.Picture_fileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Picture_fileField, value) <> true) Then
                    Me.Picture_fileField = value
                    Me.RaisePropertyChanged("Picture_file")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Replication_key() As String
            Get
                Return Me.Replication_keyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Replication_keyField, value) <> true) Then
                    Me.Replication_keyField = value
                    Me.RaisePropertyChanged("Replication_key")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sales_contact() As Boolean
            Get
                Return Me.Sales_contactField
            End Get
            Set
                If (Me.Sales_contactField.Equals(value) <> true) Then
                    Me.Sales_contactField = value
                    Me.RaisePropertyChanged("Sales_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Salutation() As String
            Get
                Return Me.SalutationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SalutationField, value) <> true) Then
                    Me.SalutationField = value
                    Me.RaisePropertyChanged("Salutation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Technical_contact() As Boolean
            Get
                Return Me.Technical_contactField
            End Get
            Set
                If (Me.Technical_contactField.Equals(value) <> true) Then
                    Me.Technical_contactField = value
                    Me.RaisePropertyChanged("Technical_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Web_site() As String
            Get
                Return Me.Web_siteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Web_siteField, value) <> true) Then
                    Me.Web_siteField = value
                    Me.RaisePropertyChanged("Web_site")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Work_extension() As Integer
            Get
                Return Me.Work_extensionField
            End Get
            Set
                If (Me.Work_extensionField.Equals(value) <> true) Then
                    Me.Work_extensionField = value
                    Me.RaisePropertyChanged("Work_extension")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Work_phone() As Long
            Get
                Return Me.Work_phoneField
            End Get
            Set
                If (Me.Work_phoneField.Equals(value) <> true) Then
                    Me.Work_phoneField = value
                    Me.RaisePropertyChanged("Work_phone")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="spc2011.SynergyServer")>  _
    Public Interface SynergyServer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SynergyServer/GetAddressForUpdate", ReplyAction:="http://tempuri.org/SynergyServer/GetAddressForUpdateResponse")>  _
        Function GetAddressForUpdate(ByVal CustomerID As Integer, ByVal AddressID As Integer, ByRef Address As spc2011.Address, ByRef GRFA() As Byte, ByRef Message As String) As spc2011.Method_status
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SynergyServer/GetAllCustomers", ReplyAction:="http://tempuri.org/SynergyServer/GetAllCustomersResponse")>  _
        Sub GetAllCustomers(ByRef Customers As System.Collections.Generic.List(Of spc2011.Customer))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SynergyServer/GetContactForUpdate", ReplyAction:="http://tempuri.org/SynergyServer/GetContactForUpdateResponse")>  _
        Function GetContactForUpdate(ByVal CustomerID As Integer, ByVal ContactID As Integer, ByRef Contact As spc2011.Contact, ByRef GRFA() As Byte, ByRef Message As String) As spc2011.Method_status
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SynergyServer/GetCustomerAddresses", ReplyAction:="http://tempuri.org/SynergyServer/GetCustomerAddressesResponse")>  _
        Sub GetCustomerAddresses(ByVal CustomerID As Integer, ByRef Addresses As System.Collections.Generic.List(Of spc2011.Address))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SynergyServer/GetCustomerContacts", ReplyAction:="http://tempuri.org/SynergyServer/GetCustomerContactsResponse")>  _
        Sub GetCustomerContacts(ByVal CustomerID As Integer, ByRef Contacts As System.Collections.Generic.List(Of spc2011.Contact))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SynergyServer/GetCustomerForUpdate", ReplyAction:="http://tempuri.org/SynergyServer/GetCustomerForUpdateResponse")>  _
        Function GetCustomerForUpdate(ByVal CustomerID As Integer, ByRef Customer As spc2011.Customer, ByRef GRFA() As Byte, ByRef Message As String) As spc2011.Method_status
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SynergyServer/UpdateContact", ReplyAction:="http://tempuri.org/SynergyServer/UpdateContactResponse")>  _
        Function UpdateContact(ByRef Contact As spc2011.Contact, ByRef GRFA() As Byte, ByRef Message As String) As spc2011.Method_status
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SynergyServer/UpdateCustomer", ReplyAction:="http://tempuri.org/SynergyServer/UpdateCustomerResponse")>  _
        Function UpdateCustomer(ByRef Customer As spc2011.Customer, ByRef GRFA() As Byte, ByRef Message As String) As spc2011.Method_status
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SynergyServerChannel
        Inherits spc2011.SynergyServer, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SynergyServerClient
        Inherits System.ServiceModel.ClientBase(Of spc2011.SynergyServer)
        Implements spc2011.SynergyServer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetAddressForUpdate(ByVal CustomerID As Integer, ByVal AddressID As Integer, ByRef Address As spc2011.Address, ByRef GRFA() As Byte, ByRef Message As String) As spc2011.Method_status Implements spc2011.SynergyServer.GetAddressForUpdate
            Return MyBase.Channel.GetAddressForUpdate(CustomerID, AddressID, Address, GRFA, Message)
        End Function
        
        Public Sub GetAllCustomers(ByRef Customers As System.Collections.Generic.List(Of spc2011.Customer)) Implements spc2011.SynergyServer.GetAllCustomers
            MyBase.Channel.GetAllCustomers(Customers)
        End Sub
        
        Public Function GetContactForUpdate(ByVal CustomerID As Integer, ByVal ContactID As Integer, ByRef Contact As spc2011.Contact, ByRef GRFA() As Byte, ByRef Message As String) As spc2011.Method_status Implements spc2011.SynergyServer.GetContactForUpdate
            Return MyBase.Channel.GetContactForUpdate(CustomerID, ContactID, Contact, GRFA, Message)
        End Function
        
        Public Sub GetCustomerAddresses(ByVal CustomerID As Integer, ByRef Addresses As System.Collections.Generic.List(Of spc2011.Address)) Implements spc2011.SynergyServer.GetCustomerAddresses
            MyBase.Channel.GetCustomerAddresses(CustomerID, Addresses)
        End Sub
        
        Public Sub GetCustomerContacts(ByVal CustomerID As Integer, ByRef Contacts As System.Collections.Generic.List(Of spc2011.Contact)) Implements spc2011.SynergyServer.GetCustomerContacts
            MyBase.Channel.GetCustomerContacts(CustomerID, Contacts)
        End Sub
        
        Public Function GetCustomerForUpdate(ByVal CustomerID As Integer, ByRef Customer As spc2011.Customer, ByRef GRFA() As Byte, ByRef Message As String) As spc2011.Method_status Implements spc2011.SynergyServer.GetCustomerForUpdate
            Return MyBase.Channel.GetCustomerForUpdate(CustomerID, Customer, GRFA, Message)
        End Function
        
        Public Function UpdateContact(ByRef Contact As spc2011.Contact, ByRef GRFA() As Byte, ByRef Message As String) As spc2011.Method_status Implements spc2011.SynergyServer.UpdateContact
            Return MyBase.Channel.UpdateContact(Contact, GRFA, Message)
        End Function
        
        Public Function UpdateCustomer(ByRef Customer As spc2011.Customer, ByRef GRFA() As Byte, ByRef Message As String) As spc2011.Method_status Implements spc2011.SynergyServer.UpdateCustomer
            Return MyBase.Channel.UpdateCustomer(Customer, GRFA, Message)
        End Function
    End Class
End Namespace
