'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace spc2011
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Customer", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Customer
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private Customer_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        Private Date_createdField As Date
        
        Private Date_modifiedField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Replication_keyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Noname_001Field As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Customer_id() As Integer
            Get
                Return Me.Customer_idField
            End Get
            Set
                If (Me.Customer_idField.Equals(value) <> true) Then
                    Me.Customer_idField = value
                    Me.RaisePropertyChanged("Customer_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Date_created() As Date
            Get
                Return Me.Date_createdField
            End Get
            Set
                If (Me.Date_createdField.Equals(value) <> true) Then
                    Me.Date_createdField = value
                    Me.RaisePropertyChanged("Date_created")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Date_modified() As Date
            Get
                Return Me.Date_modifiedField
            End Get
            Set
                If (Me.Date_modifiedField.Equals(value) <> true) Then
                    Me.Date_modifiedField = value
                    Me.RaisePropertyChanged("Date_modified")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property Replication_key() As String
            Get
                Return Me.Replication_keyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Replication_keyField, value) <> true) Then
                    Me.Replication_keyField = value
                    Me.RaisePropertyChanged("Replication_key")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property Noname_001() As String
            Get
                Return Me.Noname_001Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Noname_001Field, value) <> true) Then
                    Me.Noname_001Field = value
                    Me.RaisePropertyChanged("Noname_001")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Contact", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Contact
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private Contact_idField As Integer
        
        Private Customer_idField As Integer
        
        Private Address_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SalutationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private First_nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Last_nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Friendly_nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TitleField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartmentField As String
        
        Private Work_phoneField As Long
        
        Private Work_extensionField As Integer
        
        Private Mobile_phoneField As Long
        
        Private Home_phoneField As Long
        
        Private FaxField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Web_siteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Picture_fileField As String
        
        Private Management_contactField As Boolean
        
        Private Technical_contactField As Boolean
        
        Private Sales_contactField As Boolean
        
        Private Billing_contactField As Boolean
        
        Private General_contactField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Replication_keyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Noname_001Field As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Contact_id() As Integer
            Get
                Return Me.Contact_idField
            End Get
            Set
                If (Me.Contact_idField.Equals(value) <> true) Then
                    Me.Contact_idField = value
                    Me.RaisePropertyChanged("Contact_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Customer_id() As Integer
            Get
                Return Me.Customer_idField
            End Get
            Set
                If (Me.Customer_idField.Equals(value) <> true) Then
                    Me.Customer_idField = value
                    Me.RaisePropertyChanged("Customer_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Address_id() As Integer
            Get
                Return Me.Address_idField
            End Get
            Set
                If (Me.Address_idField.Equals(value) <> true) Then
                    Me.Address_idField = value
                    Me.RaisePropertyChanged("Address_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Salutation() As String
            Get
                Return Me.SalutationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SalutationField, value) <> true) Then
                    Me.SalutationField = value
                    Me.RaisePropertyChanged("Salutation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property First_name() As String
            Get
                Return Me.First_nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.First_nameField, value) <> true) Then
                    Me.First_nameField = value
                    Me.RaisePropertyChanged("First_name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property Last_name() As String
            Get
                Return Me.Last_nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Last_nameField, value) <> true) Then
                    Me.Last_nameField = value
                    Me.RaisePropertyChanged("Last_name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property Friendly_name() As String
            Get
                Return Me.Friendly_nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Friendly_nameField, value) <> true) Then
                    Me.Friendly_nameField = value
                    Me.RaisePropertyChanged("Friendly_name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property Title() As String
            Get
                Return Me.TitleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TitleField, value) <> true) Then
                    Me.TitleField = value
                    Me.RaisePropertyChanged("Title")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property Department() As String
            Get
                Return Me.DepartmentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartmentField, value) <> true) Then
                    Me.DepartmentField = value
                    Me.RaisePropertyChanged("Department")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=9)>  _
        Public Property Work_phone() As Long
            Get
                Return Me.Work_phoneField
            End Get
            Set
                If (Me.Work_phoneField.Equals(value) <> true) Then
                    Me.Work_phoneField = value
                    Me.RaisePropertyChanged("Work_phone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=10)>  _
        Public Property Work_extension() As Integer
            Get
                Return Me.Work_extensionField
            End Get
            Set
                If (Me.Work_extensionField.Equals(value) <> true) Then
                    Me.Work_extensionField = value
                    Me.RaisePropertyChanged("Work_extension")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=11)>  _
        Public Property Mobile_phone() As Long
            Get
                Return Me.Mobile_phoneField
            End Get
            Set
                If (Me.Mobile_phoneField.Equals(value) <> true) Then
                    Me.Mobile_phoneField = value
                    Me.RaisePropertyChanged("Mobile_phone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=12)>  _
        Public Property Home_phone() As Long
            Get
                Return Me.Home_phoneField
            End Get
            Set
                If (Me.Home_phoneField.Equals(value) <> true) Then
                    Me.Home_phoneField = value
                    Me.RaisePropertyChanged("Home_phone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=13)>  _
        Public Property Fax() As Long
            Get
                Return Me.FaxField
            End Get
            Set
                If (Me.FaxField.Equals(value) <> true) Then
                    Me.FaxField = value
                    Me.RaisePropertyChanged("Fax")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property Web_site() As String
            Get
                Return Me.Web_siteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Web_siteField, value) <> true) Then
                    Me.Web_siteField = value
                    Me.RaisePropertyChanged("Web_site")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=16)>  _
        Public Property Picture_file() As String
            Get
                Return Me.Picture_fileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Picture_fileField, value) <> true) Then
                    Me.Picture_fileField = value
                    Me.RaisePropertyChanged("Picture_file")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=17)>  _
        Public Property Management_contact() As Boolean
            Get
                Return Me.Management_contactField
            End Get
            Set
                If (Me.Management_contactField.Equals(value) <> true) Then
                    Me.Management_contactField = value
                    Me.RaisePropertyChanged("Management_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=18)>  _
        Public Property Technical_contact() As Boolean
            Get
                Return Me.Technical_contactField
            End Get
            Set
                If (Me.Technical_contactField.Equals(value) <> true) Then
                    Me.Technical_contactField = value
                    Me.RaisePropertyChanged("Technical_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=19)>  _
        Public Property Sales_contact() As Boolean
            Get
                Return Me.Sales_contactField
            End Get
            Set
                If (Me.Sales_contactField.Equals(value) <> true) Then
                    Me.Sales_contactField = value
                    Me.RaisePropertyChanged("Sales_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=20)>  _
        Public Property Billing_contact() As Boolean
            Get
                Return Me.Billing_contactField
            End Get
            Set
                If (Me.Billing_contactField.Equals(value) <> true) Then
                    Me.Billing_contactField = value
                    Me.RaisePropertyChanged("Billing_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=21)>  _
        Public Property General_contact() As Boolean
            Get
                Return Me.General_contactField
            End Get
            Set
                If (Me.General_contactField.Equals(value) <> true) Then
                    Me.General_contactField = value
                    Me.RaisePropertyChanged("General_contact")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=22)>  _
        Public Property Replication_key() As String
            Get
                Return Me.Replication_keyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Replication_keyField, value) <> true) Then
                    Me.Replication_keyField = value
                    Me.RaisePropertyChanged("Replication_key")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=23)>  _
        Public Property Noname_001() As String
            Get
                Return Me.Noname_001Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Noname_001Field, value) <> true) Then
                    Me.Noname_001Field = value
                    Me.RaisePropertyChanged("Noname_001")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Method_status", [Namespace]:="http://tempuri.org/")>  _
    Public Enum Method_status As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Success = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Info_error = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Fatal_error = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="spc2011.WebServiceSoap")>  _
    Public Interface WebServiceSoap
        
        'CODEGEN: Generating message contract since element name GetAllCustomersResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetAllCustomers", ReplyAction:="*")>  _
        Function GetAllCustomers(ByVal request As spc2011.GetAllCustomersRequest) As spc2011.GetAllCustomersResponse
        
        'CODEGEN: Generating message contract since element name GetCustomerContactsResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetCustomerContacts", ReplyAction:="*")>  _
        Function GetCustomerContacts(ByVal request As spc2011.GetCustomerContactsRequest) As spc2011.GetCustomerContactsResponse
        
        'CODEGEN: Generating message contract since element name contact from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetContactForUpdate", ReplyAction:="*")>  _
        Function GetContactForUpdate(ByVal request As spc2011.GetContactForUpdateRequest) As spc2011.GetContactForUpdateResponse
        
        'CODEGEN: Generating message contract since element name contact from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateContact", ReplyAction:="*")>  _
        Function UpdateContact(ByVal request As spc2011.UpdateContactRequest) As spc2011.UpdateContactResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAllCustomersRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAllCustomers", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As spc2011.GetAllCustomersRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As spc2011.GetAllCustomersRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetAllCustomersRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetAllCustomersResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetAllCustomersResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As spc2011.GetAllCustomersResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As spc2011.GetAllCustomersResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetAllCustomersResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetAllCustomersResult As System.Collections.Generic.List(Of spc2011.Customer)
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetAllCustomersResult As System.Collections.Generic.List(Of spc2011.Customer))
            MyBase.New
            Me.GetAllCustomersResult = GetAllCustomersResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetCustomerContactsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetCustomerContacts", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As spc2011.GetCustomerContactsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As spc2011.GetCustomerContactsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetCustomerContactsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public CustomerId As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CustomerId As Integer)
            MyBase.New
            Me.CustomerId = CustomerId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetCustomerContactsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetCustomerContactsResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As spc2011.GetCustomerContactsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As spc2011.GetCustomerContactsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetCustomerContactsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetCustomerContactsResult As System.Collections.Generic.List(Of spc2011.Contact)
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetCustomerContactsResult As System.Collections.Generic.List(Of spc2011.Contact))
            MyBase.New
            Me.GetCustomerContactsResult = GetCustomerContactsResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetContactForUpdateRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetContactForUpdate", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As spc2011.GetContactForUpdateRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As spc2011.GetContactForUpdateRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetContactForUpdateRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public customerId As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public contactId As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public contact As spc2011.Contact
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public grfa() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public msg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal customerId As Integer, ByVal contactId As Integer, ByVal contact As spc2011.Contact, ByVal grfa() As Byte, ByVal msg As String)
            MyBase.New
            Me.customerId = customerId
            Me.contactId = contactId
            Me.contact = contact
            Me.grfa = grfa
            Me.msg = msg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetContactForUpdateResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetContactForUpdateResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As spc2011.GetContactForUpdateResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As spc2011.GetContactForUpdateResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetContactForUpdateResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetContactForUpdateResult As spc2011.Method_status
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public contact As spc2011.Contact
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public grfa() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetContactForUpdateResult As spc2011.Method_status, ByVal contact As spc2011.Contact, ByVal grfa() As Byte)
            MyBase.New
            Me.GetContactForUpdateResult = GetContactForUpdateResult
            Me.contact = contact
            Me.grfa = grfa
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateContactRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateContact", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As spc2011.UpdateContactRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As spc2011.UpdateContactRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UpdateContactRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public contact As spc2011.Contact
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public grfa() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public msg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal contact As spc2011.Contact, ByVal grfa() As Byte, ByVal msg As String)
            MyBase.New
            Me.contact = contact
            Me.grfa = grfa
            Me.msg = msg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateContactResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateContactResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As spc2011.UpdateContactResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As spc2011.UpdateContactResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class UpdateContactResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public UpdateContactResult As spc2011.Method_status
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public contact As spc2011.Contact
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public grfa() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public msg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UpdateContactResult As spc2011.Method_status, ByVal contact As spc2011.Contact, ByVal grfa() As Byte, ByVal msg As String)
            MyBase.New
            Me.UpdateContactResult = UpdateContactResult
            Me.contact = contact
            Me.grfa = grfa
            Me.msg = msg
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebServiceSoapChannel
        Inherits spc2011.WebServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of spc2011.WebServiceSoap)
        Implements spc2011.WebServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function spc2011_WebServiceSoap_GetAllCustomers(ByVal request As spc2011.GetAllCustomersRequest) As spc2011.GetAllCustomersResponse Implements spc2011.WebServiceSoap.GetAllCustomers
            Return MyBase.Channel.GetAllCustomers(request)
        End Function
        
        Public Function GetAllCustomers() As System.Collections.Generic.List(Of spc2011.Customer)
            Dim inValue As spc2011.GetAllCustomersRequest = New spc2011.GetAllCustomersRequest()
            inValue.Body = New spc2011.GetAllCustomersRequestBody()
            Dim retVal As spc2011.GetAllCustomersResponse = CType(Me,spc2011.WebServiceSoap).GetAllCustomers(inValue)
            Return retVal.Body.GetAllCustomersResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function spc2011_WebServiceSoap_GetCustomerContacts(ByVal request As spc2011.GetCustomerContactsRequest) As spc2011.GetCustomerContactsResponse Implements spc2011.WebServiceSoap.GetCustomerContacts
            Return MyBase.Channel.GetCustomerContacts(request)
        End Function
        
        Public Function GetCustomerContacts(ByVal CustomerId As Integer) As System.Collections.Generic.List(Of spc2011.Contact)
            Dim inValue As spc2011.GetCustomerContactsRequest = New spc2011.GetCustomerContactsRequest()
            inValue.Body = New spc2011.GetCustomerContactsRequestBody()
            inValue.Body.CustomerId = CustomerId
            Dim retVal As spc2011.GetCustomerContactsResponse = CType(Me,spc2011.WebServiceSoap).GetCustomerContacts(inValue)
            Return retVal.Body.GetCustomerContactsResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function spc2011_WebServiceSoap_GetContactForUpdate(ByVal request As spc2011.GetContactForUpdateRequest) As spc2011.GetContactForUpdateResponse Implements spc2011.WebServiceSoap.GetContactForUpdate
            Return MyBase.Channel.GetContactForUpdate(request)
        End Function
        
        Public Function GetContactForUpdate(ByVal customerId As Integer, ByVal contactId As Integer, ByRef contact As spc2011.Contact, ByRef grfa() As Byte, ByVal msg As String) As spc2011.Method_status
            Dim inValue As spc2011.GetContactForUpdateRequest = New spc2011.GetContactForUpdateRequest()
            inValue.Body = New spc2011.GetContactForUpdateRequestBody()
            inValue.Body.customerId = customerId
            inValue.Body.contactId = contactId
            inValue.Body.contact = contact
            inValue.Body.grfa = grfa
            inValue.Body.msg = msg
            Dim retVal As spc2011.GetContactForUpdateResponse = CType(Me,spc2011.WebServiceSoap).GetContactForUpdate(inValue)
            contact = retVal.Body.contact
            grfa = retVal.Body.grfa
            Return retVal.Body.GetContactForUpdateResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function spc2011_WebServiceSoap_UpdateContact(ByVal request As spc2011.UpdateContactRequest) As spc2011.UpdateContactResponse Implements spc2011.WebServiceSoap.UpdateContact
            Return MyBase.Channel.UpdateContact(request)
        End Function
        
        Public Function UpdateContact(ByRef contact As spc2011.Contact, ByRef grfa() As Byte, ByRef msg As String) As spc2011.Method_status
            Dim inValue As spc2011.UpdateContactRequest = New spc2011.UpdateContactRequest()
            inValue.Body = New spc2011.UpdateContactRequestBody()
            inValue.Body.contact = contact
            inValue.Body.grfa = grfa
            inValue.Body.msg = msg
            Dim retVal As spc2011.UpdateContactResponse = CType(Me,spc2011.WebServiceSoap).UpdateContact(inValue)
            contact = retVal.Body.contact
            grfa = retVal.Body.grfa
            msg = retVal.Body.msg
            Return retVal.Body.UpdateContactResult
        End Function
    End Class
End Namespace
